### ISSUE TITLE
파일 당 크기 제한

### ISSUE THREAD

**Issue by NamGungGeon** [brotherstone97/CPSP_OCRServer_DRF#2]

**Comment by brotherstone97** [comment]
TO DO LIST
--------------
1. 단일 파일 용량 제한(50MB)
2. PIL라이브러리 활용, 이미지 다운사이징
3. README.md 내 dependency 갱신

**Comment by brotherstone97** [comment]
50mb로 제한 후 pillow를 이용한 optimizing으로 file size축소
